[package]
name = "opex"
version = "0.1.0"
edition = "2021"

[lib]
name = "opex"
crate-type=["dylib"]

[dependencies]
ebi_source = { path = "../../ebi_source" }
ebi_source_macros = { path = "../../ebi_source_macros" }
